on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-1
      - name: Build and push image to ECR
        run: |
          $(aws ecr get-login-password --region ap-northeast-1)
          docker build -t react-admin .
          docker tag react-admin 377920307585.dkr.ecr.ap-northeast-1.amazonaws.com/lantron-ecr-b5b2b12/react-admin:latest
          docker push 377920307585.dkr.ecr.ap-northeast-1.amazonaws.com/lantron-ecr-b5b2b12/react-admin:latest
